# Generated by Django 4.2 on 2023-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manoApps", "0002_remove_asmenys_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="asmenys",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Amžius"
            ),
        ),
    ]
