# Generated by Django 4.2 on 2023-04-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manoApps", "0003_asmenys_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asmenys",
            old_name="age",
            new_name="user_age",
        ),
    ]
