# Generated by Django 4.2 on 2023-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manoApps", "0004_rename_age_asmenys_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asmenys",
            name="user_age",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Amžius"
            ),
        ),
    ]
